### PR TITLE
慣 missing stroke four

### PR DESCRIPTION
**Pull request by SirenHound**
I think this one is worth pulling, (sorry about before).

This Kanji 慣 wasn't rendering stroke four, I think I've fixed it now but could you double check?

### CODE REVIEW

**Comment by SirenHound** [comment]
pre-fix: (http://nippongrammar.appspot.com/)
screen shot 2015-08-30 at 7 54 59 pm

post-fix: (my project)
screen shot 2015-08-30 at 7 58 26 pm

Stroke order is correct.

**Comment by aarond10** [comment]
Thanks for the report (and fix)!

It actually looks like this is an upstream data problem. (My data is generated from kanjivg.)
https://groups.google.com/forum/#!msg/kanjivg/B47-UFytiAU/iN3oO4BKCrgJ

I haven't been good at keeping this up to date. The dataset I'm using is from May 2010. I'll update it tomorrow and see if that fixes it. If not, I'll try and push your fix up into kanjivg.

**Comment by SirenHound** [comment]
http://kanjivg.tagaini.net/ was where I got the stroke to include, so I think they already have it.

I didn't know how you generate from them, but I knew you did since you're in the list of projects using KanjiVG.

I just thought that stroke might have been lost somewhere in the conversion.

By the way,
I am using your code for a Userscript to animate reviews and lessons on WaniKani.

**Comment by aarond10** [comment]
FYI: Got half way through this and dragged overseas for work. The data
format has changed since I wrote my terrible import script. I suspect I
misinterpreted the SVG standard as well as some of the curves aren't
working right. Haven't forgotten this though. I'll fix when I get back.

**Pull request closed without merging**
